### ISSUE TITLE
bug: `PersistedS3ObjectStore.open() got an unexpected keyword argument 'mode'` in v3

### ISSUE THREAD

**Issue by ihmpavel** [GREsau/localstack-persist#10]
Hi, thank you for the amazing project! Unfortunately I encountered an issue after upgrading to the latest version.

In Node JS, after upgrading to version `>= 3.0.0`

```
const s3 = new S3Client({
  // region: 'us-west-1',
  forcePathStyle: true,
  // endpoint: 'http://localhost:4566',
})

s3.send(
  new PutObjectCommand({
    Bucket: 'mybucket',
    Key: 'image.png',
    Body: fs.readFileSync('image.png'),
  })
)
```

Leads to throwing an error

```
/pathToProject/node_modules/@smithy/smithy-client/dist-cjs/index.js:838
  const response = new exceptionCtor({
                   ^
S3ServiceException [InternalError]: exception while calling s3.PutObject: PersistedS3ObjectStore.open() got an unexpected keyword argument 'mode'
    at throwDefaultError (/pathToProject/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /pathToProject/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_CommandError (/pathToProject/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /pathToProject/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /pathToProject/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:225:18
    at async /pathToProject/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /pathToProject/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:173:18
    at async /pathToProject/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20
    at async /pathToProject/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 500,
    requestId: '72d0bfbc-84b6-43c8-8d95-1108cf601475',
    extendedRequestId: 's9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=',
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 157
  },
  Code: 'InternalError',
  RequestId: '72d0bfbc-84b6-43c8-8d95-1108cf601475'
}
```

I am not sure, why is this happening.

I suppose the code is not working somewhere in the class https://github.com/GREsau/localstack-persist/blob/main/src/localstack_persist/s3/storage.py#L35

What is the best way to debug/fix this?

**Comment by GREsau** [comment]
Thanks for the report, this should now be fixed in `localstack-persist:latest`.

There was a breaking change to the S3 storage code in localstack, so I had to make a corresponding change here to restore compatibility.

This should have been caught by the automated tests, but unfortunately that didn't happen because the tests were mistakenly running against `locakstack:3` even when the actual image being pushed to Docker Hubwas based on `localstack:latest`. That's also now fixed, which should prevent bugs like this from being pushed to Docker Hub again 🤞
